# Site setings
name: 'VeryNOISE'
description: 'Todo el ruido que tu mente necesita'
# Sidebar about text
site_description: 'Un extenso catálogo de lo más bizarro que se ha cruzado por la internet'
logo:
favicon: 'assets/images/favicon.ico'
baseurl: https://verynoise.com/
production_url: https://verynoise.com/
disqus: 'justgoodthemes'
mailchimp_url:
# Add your GA Tracking Id
ga_analytics:

# Contact form setings
email: pedrol@mego.cl
contact_page_description: ""
thankyou_page_description: "Su mensaje ha sido enviado con éxito. Nos contactaremos contigo muy pronto!"

# Social links
twitter: '@robok'
facebook: 'username'
github: '@robok3000'
medium: '@username'
instagram: '@robok3000'
pinterest: 'username'
linkedin: 'username'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Style Guide
    url: /style-guide/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-author-page

# Pagination
paginate: 6
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
