# Site setings
name: 'VeryNOISE'
description: 'Todo el ruido que tu mente necesita'
# Sidebar about text
site_description: 'Una revista enfocada en la nueva música que surje de todos los rincones de este universo'
logo:
favicon: 'assets/images/favicon.ico'
baseurl:
production_url: https://www.verynoise.com/
disqus: 'justgoodthemes'
mailchimp_url: '//verynoise.us8.list-manage.com/subscribe/post?u=be9009537a869a19910f03ffd&amp;id=ed71eafa26'
# Add your GA Tracking Id
ga_analytics: 'UA-50933804-20'

# Contact form setings
email: hola@verynoise.com
contact_page_description: "Si tienes algo interesante que quieras promocionar o necesitas hablar conmigo, puedes enviarme un correo. Me interesan todas las ideas."
thankyou_page_description: "Tu mensaje ya fue recibido por nuestro hamster dj. Te responderá a la brevedad!"

# Social links
twitter: 'verynoise_com'
facebook: 'VeryNoise3000'
instagram: 'very.noise'

# Navigation
navigation:
  - text: Acerca de mi
    url: /about
  - text: Contactame
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-author-page

# Pagination
paginate: 6
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
